<?php

namespace Database\Seeders;

use App\Models\Beneficio;
use App\Models\Tipo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TipoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tipo = [
            ['codigo' => 'L.1', 'porcentaje_base' => '0.04'],
            ['codigo' => 'L.2', 'porcentaje_base' => '0.05'],
            ['codigo' => 'L3', 'porcentaje_base' => '0.04'],
            ['codigo' => 'L.4', 'porcentaje_base' => '0.04'],
            ['codigo' => 'L.5', 'porcentaje_base' => '0.04'],
            ['codigo' => 'L.6', 'porcentaje_base' => '0.04'],
            ['codigo' => 'L.7', 'porcentaje_base' => '0.04'],
            ['codigo' => 'L.8', 'porcentaje_base' => '0.04'],
            ['codigo' => 'G', 'porcentaje_base' => '0.08'],
            ['codigo' => 'M.10', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.11', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M13', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M14', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.15', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.18', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.19', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.22', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.24', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.25', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.26', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M30', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.34', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.35', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.36', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.40', 'porcentaje_base' => '0.05'],
            ['codigo' => 'M.41', 'porcentaje_base' => '1.5'],

            //no aplica descuento base - dias y documento.
            ['codigo' => 'M12', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.16', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M17', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.21', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.23', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.28', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M.29', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M31', 'porcentaje_base' => '0.12'],
            ['codigo' => 'M32', 'porcentaje_base' => '0.12'],

            ['codigo' => 'M.6', 'porcentaje_base' => '0.24'],
            ['codigo' => 'M7', 'porcentaje_base' => '0.24'],
            ['codigo' => 'M.8', 'porcentaje_base' => '0.24'],
            ['codigo' => 'M.9', 'porcentaje_base' => '0.24'],

            ['codigo' => 'M.20', 'porcentaje_base' => '0.18'],
            ['codigo' => 'M.2', 'porcentaje_base' => '0.5'],
            ['codigo' => 'M.3', 'porcentaje_base' => '0.5'],
            ['codigo' => 'M.5', 'porcentaje_base' => '0.5'],
            ['codigo' => 'M.27', 'porcentaje_base' => '0.5'],
            ['codigo' => 'M.1', 'porcentaje_base' => '1'],
            ['codigo' => 'M.4', 'porcentaje_base' => '1'],
            ['codigo' => 'M.42', 'porcentaje_base' => '0.05'],
            //cierre de no aplica.

            //sin costo
            ['codigo' => 'M.37', 'porcentaje_base' => '0'],
            ['codigo' => 'M.38', 'porcentaje_base' => '0'],
            ['codigo' => 'M.39', 'porcentaje_base' => '0'],

            ['codigo' => 'PF1', 'porcentaje_base' => '1'],
            ['codigo' => 'PF2', 'porcentaje_base' => '0.25'],
            ['codigo' => 'PF3', 'porcentaje_base' => '0.1'],
            ['codigo' => 'PF4', 'porcentaje_base' => '0.05'],
            ['codigo' => 'PI1', 'porcentaje_base' => '0.5'],
            ['codigo' => 'PI2', 'porcentaje_base' => '1'],
            ['codigo' => 'PI3', 'porcentaje_base' => '0.25'],
            ['codigo' => 'PI4', 'porcentaje_base' => '0.25'],
            ['codigo' => 'PI5', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PI6', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'PI7', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PI8', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PI9', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PI10', 'porcentaje_base' => '0.08'],
            [ 'codigo' => 'PI11', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PI12', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS1', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'PS2', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS3', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS4', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS5', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'PS6', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS7', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS8', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS9', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'PS10', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'PS11', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'PS12', 'porcentaje_base' => '0.24'],
            [ 'codigo' => 'PS13', 'porcentaje_base' => '0.24'],
            [ 'codigo' => 'PS14', 'porcentaje_base' => '0.24'],
            [ 'codigo' => 'PS15', 'porcentaje_base' => '0.24'],
            [ 'codigo' => 'PS16', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS17', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS18', 'porcentaje_base' => '0.25'],
            [ 'codigo' => 'PS19', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS20', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS21', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS22', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS23', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS24', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS25', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS26', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS27', 'porcentaje_base' => '0.1'],
            [ 'codigo' => 'PS28', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS29', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS30', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS31', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS32', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS33', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS34', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS35', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS36', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS37', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS38', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS39', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS40', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'PS41', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ID1', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'ID2', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ID3', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ID4', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ID5', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ID6', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ID7', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ID8', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'ID9', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ID10', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ID11', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ID12', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ID13', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ID14', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC1', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IC2', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IC3', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IC4', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC5', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC6', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC7', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC8', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC9', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC10', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC11', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC12', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC13', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC14', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC15', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC16', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IC17', 'porcentaje_base' => '0.026'],
            [ 'codigo' => 'IC18', 'porcentaje_base' => '0.026'],
            [ 'codigo' => 'DC1', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'DC2', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'DC3', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'DC4', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'DC5', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'DC6', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'DC7', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'DC8', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'DC9', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS1', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS2', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS3', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS4', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS5', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS6', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS7', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS8', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS9', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS10', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS11', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS12', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS13', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS14', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS15', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS16', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS17', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS18', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IS19', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS20', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS21', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS22', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS23', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS24', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS25', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS26', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS27', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS28', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS29', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS30', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS31', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IS32', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IV1', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'IV2', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IV3', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IV4', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'IV5', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ED1', 'porcentaje_base' => '0.05'],
            [ 'codigo' => 'ED2', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ED3', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ED4', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ED5', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ED6', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ED7', 'porcentaje_base' => '0.045'],
            [ 'codigo' => 'ED8', 'porcentaje_base' => '0.026'],
            [ 'codigo' => 'ED9', 'porcentaje_base' => '0.026'],
            [ 'codigo' => 'MAT1', 'porcentaje_base' => '0.5'],
            [ 'codigo' => 'P1', 'porcentaje_base' => '0.08'],
            [ 'codigo' => 'P2', 'porcentaje_base' => '0.08'],
            [ 'codigo' => 'P3', 'porcentaje_base' => '0.04'],
            [ 'codigo' => 'P4', 'porcentaje_base' => '0.04'],
            [ 'codigo' => 'AC1', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'AC2', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'AC3', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'AC4', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'AC5', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'AC6', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'AC7', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'AC8', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC9', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC10', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC11', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC12', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC13', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC14', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC15', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC16', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC17', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'AC18', 'porcentaje_base' => '0.003'],
            [ 'codigo' => 'AC19', 'porcentaje_base' => '0.003'],
            [ 'codigo' => 'BC1', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'BC2', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'BC3', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'BC4', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'BC5', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS1', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'CS2', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'CS3', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'CS4', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'CS5', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS6', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS7', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS8', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS9', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS10', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS11', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS12', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'CS13', 'porcentaje_base' => '0.003'],
            [ 'codigo' => 'DV1', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'DV2', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'DV3', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'DV4', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'ED1', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'ED2', 'porcentaje_base' => '0.01'],
            [ 'codigo' => 'ED3', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'ED4', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'ED5', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'FD1', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'FD2', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'FD3', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'FD4', 'porcentaje_base' => '0.005'],
            [ 'codigo' => 'FD5', 'porcentaje_base' => '0.005'],
        ];

        foreach($tipo as $tip){
            Tipo::create($tip);
        }

    }
}
